import { z } from "zod";

export const propertySchema = z.object({
  title: z.string().min(1, "Title is required"),
  slug: z.string().optional(),
  description: z.string().nullable().optional(),
  short_description: z.string().max(160).nullable().optional(),
  type: z.enum(["sale", "rent"]),
  status: z.enum(["active", "sold", "rented", "draft"]).default("active"),
  category_id: z.string().uuid().nullable().optional(),
  price: z.number().min(0),
  price_label: z.string().nullable().optional(),
  area_sqft: z.number().min(0).nullable().optional(),
  bedrooms: z.number().int().min(0).nullable().optional(),
  bathrooms: z.number().int().min(0).nullable().optional(),
  floors: z.number().int().min(0).nullable().optional(),
  facing: z.string().nullable().optional(),
  age_years: z.number().int().min(0).nullable().optional(),
  furnished: z.enum(["furnished", "semi-furnished", "unfurnished"]).nullable().optional(),
  address: z.string().min(1, "Address is required"),
  city: z.string().min(1, "City is required"),
  state: z.string().min(1, "State is required"),
  zip_code: z.string().nullable().optional(),
  country: z.string().default("India"),
  latitude: z.number().nullable().optional(),
  longitude: z.number().nullable().optional(),
  map_embed_url: z.string().url().nullable().or(z.literal("")).optional(),
  cover_image_url: z.string().url().nullable().or(z.literal("")).optional(),
  gallery_images: z.array(z.string().url()).nullable().optional(),
  amenities: z.array(z.string()).nullable().optional(),
  highlights: z.array(z.string()).nullable().optional(),
  plot_number: z.string().nullable().optional(),
  plot_dimensions: z.string().nullable().optional(),
  meta_title: z.string().nullable().optional(),
  meta_description: z.string().nullable().optional(),
  meta_keywords: z.string().nullable().optional(),
  og_image_url: z.string().url().nullable().or(z.literal("")).optional(),
});

export type PropertyFormValues = z.infer<typeof propertySchema>;
